# Generated by Django 3.2.11 on 2022-01-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=100, verbose_name='名称')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
            ],
            options={
                'verbose_name': '动物',
            },
        ),
    ]
