# Generated by Django 3.2.11 on 2022-01-16 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(db_index=True, default='', max_length=16, verbose_name='年级名称')),
            ],
            options={
                'verbose_name': '年级',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(db_index=True, default='', max_length=16, verbose_name='学生名称')),
                ('s_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade', to='ViewStudy.grade')),
            ],
            options={
                'verbose_name': '学生',
            },
        ),
    ]
