# Generated by Django 3.2.11 on 2022-01-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewStudy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_token',
            field=models.CharField(default='', max_length=256, verbose_name='token'),
        ),
    ]
