# Generated by Django 3.2.11 on 2022-01-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewStudy', '0002_student_s_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_password',
            field=models.CharField(default='', max_length=128, verbose_name='密码'),
        ),
    ]
