# Generated by Django 3.2.11 on 2022-01-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRFStudy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='bread',
            new_name='b_read',
        ),
    ]
