# Generated by Django 3.2.11 on 2022-01-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileStudy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=16, unique=True, verbose_name='用户名'),
        ),
    ]
