# Generated by Django 3.2.11 on 2022-01-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(default='', max_length=32, verbose_name='书名')),
                ('b_price', models.FloatField(default=1, verbose_name='价格')),
            ],
            options={
                'verbose_name': '书',
            },
        ),
    ]
